name: Build and deploy Python app to Azure Web App - ba-agent-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp -r *.py requirements.txt app.py deploy/
          # Include other folders if needed, e.g., templates, static
          # cp -r templates deploy/templates
          # cp -r static deploy/static

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: List downloaded files (debug)
        run: |
          ls -la
          ls -la deploy/ || echo "No deploy folder found"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9899BFBB0D3D4964BCA9E9D29D35278D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A9EB8545455045E0914BD67D690AE82B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A3DA5A2CB39049CBB1D9D462C7041EDA }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ba-agent-backend'
          slot-name: 'Production'
          package: ./deploy

      - name: Set Startup Command
        run: |
          az webapp config set \
            --name ba-agent-backend \
            --resource-group chatpdf \
            --startup-file "python /home/site/wwwroot/app.py runserver 0.0.0.0:8000"

