name: Build and Deploy Python App to Azure Web App - ba-agent-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Prepare deployment package
        run: |
          mkdir -p deploy

          # Copy Python files if they exist
          shopt -s nullglob
          py_files=(*.py)
          if [ ${#py_files[@]} -gt 0 ]; then
            cp -r "${py_files[@]}" deploy/
          fi

          # Copy requirements.txt if it exists
          [ -f requirements.txt ] && cp requirements.txt deploy/

          # Copy additional folders if they exist
          [ -d templates ] && cp -r templates deploy/templates
          [ -d static ] && cp -r static deploy/static

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Ensure deploy folder exists
        run: |
          mkdir -p deploy
          mv * deploy/ || echo "No files found to move into deploy/"

      - name: List deploy folder (debug)
        run: ls -la deploy/

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9899BFBB0D3D4964BCA9E9D29D35278D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A9EB8545455045E0914BD67D690AE82B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A3DA5A2CB39049CBB1D9D462C7041EDA }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ba-agent-backend'
          slot-name: 'Production'
          package: ./deploy

      - name: Set Startup Command
        run: |
          az webapp config set \
            --name ba-agent-backend \
            --resource-group chatpdf \
            --startup-file "python /home/site/wwwroot/app.py runserver 0.0.0.0:8000"
