name: Build and deploy Python app to Azure Web App - ba-agent-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: run tests
      # - name: Run tests
      #   run: pytest

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            ./**/*.py
            requirements.txt
            manage.py
            !venv/
            !.git/
            !.github/
            !output*.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9899BFBB0D3D4964BCA9E9D29D35278D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A9EB8545455045E0914BD67D690AE82B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A3DA5A2CB39049CBB1D9D462C7041EDA }}

      # Cleanup old files before deployment
      - name: Clean /wwwroot before deploy
        run: |
          az webapp ssh --name ba-agent-backend --resource-group chatpdf --command "rm -rf /home/site/wwwroot/*"

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'ba-agent-backend'
          slot-name: 'production'

      # Optional: set startup command (replace with your framework)
      # - name: Set Startup Command
      #   run: |
      #     az webapp config set \
      #       --name ba-agent-backend \
      #       --resource-group <your-rg> \
      #       --startup-file "gunicorn --bind=0.0.0.0 --timeout 600 app:app"
 